#!/usr/bin/env python3
"""
Generate the CIRQUA field-service QR code set and printable node labels.

Every QR code encodes a PERMANENT documentation URL on the deployed GitHub
Pages site. Localhost and preview URLs are never encoded, because a label
printed in the field must keep working long after this script has run.

URL shape
---------
The site is built with ``use_directory_urls: false`` (WattLab standard), so
page URLs are flat ``.html`` files:

    https://lestealthy.github.io/Cirqua-documentation/nodes/node1.html

Usage
-----
    python scripts/generate_qr_codes.py
    python scripts/generate_qr_codes.py --check
"""

from __future__ import annotations

import argparse
import io
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import qrcode
    from qrcode.constants import ERROR_CORRECT_H
except ImportError:  # pragma: no cover
    sys.exit("qrcode is required. Install with: pip install qrcode")


REPO_ROOT = Path(__file__).resolve().parent.parent
QR_DIR = REPO_ROOT / "docs" / "assets" / "qr"

SITE_BASE = "https://lestealthy.github.io/Cirqua-documentation"


@dataclass(frozen=True)
class QrTarget:
    key: str
    node_label: str
    slug: str
    purpose: str
    is_node: bool = True


TARGETS: tuple[QrTarget, ...] = (
    QrTarget("node1", "CIRQUA NODE 1", "nodes/node1", "Collection Tank A level, cluster head"),
    QrTarget("node2", "CIRQUA NODE 2", "nodes/node2", "Water temperature, dissolved oxygen, Tank B level"),
    QrTarget("node3", "CIRQUA NODE 3", "nodes/node3", "Flow metering and telemetry forwarding"),
    QrTarget("node4", "CIRQUA NODE 4", "nodes/node4", "Effluent pH, turbidity, conductivity, level"),
    QrTarget("node4-smtp", "CIRQUA NODE 4 SMTP", "nodes/node4-smtp", "Node 4 with e-mail alerting"),
    QrTarget("troubleshooting", "CIRQUA TROUBLESHOOTING", "field-service/troubleshooting", "Symptom-driven fault finding", is_node=False),
    QrTarget("calibration", "CIRQUA CALIBRATION", "calibration/index", "Calibration procedures and constants", is_node=False),
    QrTarget("startup", "CIRQUA STARTUP", "field-service/startup-checklist", "Power-up verification checklist", is_node=False),
    QrTarget("home", "CIRQUA DOCUMENTATION", "index", "Documentation home", is_node=False),
)


def destination(slug: str) -> str:
    """Permanent, stable documentation URL for a page slug."""
    if slug == "index":
        return f"{SITE_BASE}/"
    return f"{SITE_BASE}/{slug}.html"


def build_qr(url: str):
    qr = qrcode.QRCode(
        version=None,
        error_correction=ERROR_CORRECT_H,  # survives label wear and dirt
        box_size=10,
        border=2,
    )
    qr.add_data(url)
    qr.make(fit=True)
    return qr.make_image(fill_color="#0A051B", back_color="white")


def _pixels(url: str):
    """Decoded pixel content for a QR code, used for drift detection.

    Pixel data is compared rather than raw file bytes: PNG encoding is not
    byte-stable across Pillow versions or platforms, so a byte comparison would
    report a false "stale" result on CI even when the code is identical.
    Comparing the decoded image makes the check content-based and reproducible.
    """
    return build_qr(url).convert("1")


def _same_pixels(path: Path, url: str) -> bool:
    try:
        from PIL import Image
    except ImportError:  # pragma: no cover
        return path.read_bytes() == _png_bytes_fallback(url)
    if not path.is_file():
        return False
    try:
        with Image.open(path) as existing:
            existing = existing.convert("1")
            expected = _pixels(url)
            if existing.size != expected.size:
                return False
            return list(existing.getdata()) == list(expected.getdata())
    except Exception:  # noqa: BLE001
        return False


def _png_bytes_fallback(url: str) -> bytes:
    buffer = io.BytesIO()
    build_qr(url).save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the QR images on disk match the current destination URLs",
    )
    args = parser.parse_args()

    QR_DIR.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    stale: list[str] = []

    for target in TARGETS:
        url = destination(target.slug)
        png_path = QR_DIR / f"qr-{target.key}.png"

        if _same_pixels(png_path, url):
            continue

        if args.check:
            stale.append(f"{target.key} (missing)" if not png_path.is_file() else target.key)
        else:
            png_path.write_bytes(_png_bytes_fallback(url))
            written.append(target.key)

    # ---- destination manifest for the documentation and CI -------------
    lines: list[str] = [
        "# Generated by scripts/generate_qr_codes.py - do not edit by hand.",
        "#",
        "# Each entry records a permanent documentation URL encoded in the",
        "# corresponding QR image. The validator re-checks these against the",
        "# built site so a stale code can never ship.",
        "",
        "site_base: " + SITE_BASE,
        "url_scheme: flat-html",
        "targets:",
    ]
    for target in TARGETS:
        lines.append(f"  - key: {target.key}")
        lines.append(f"    label: \"{target.node_label}\"")
        lines.append(f"    slug: {target.slug}")
        lines.append(f"    url: {destination(target.slug)}")
        lines.append(f"    image: assets/qr/qr-{target.key}.png")
        lines.append(f"    is_node_label: {'true' if target.is_node else 'false'}")
        lines.append(f"    purpose: {target.purpose}")
    (QR_DIR / "qr-targets.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"site base   : {SITE_BASE}/")
    print(f"targets     : {len(TARGETS)}")
    print(f"output      : {QR_DIR.relative_to(REPO_ROOT)}")

    if args.check:
        if stale:
            print(f"\nSTALE: {', '.join(stale)}")
            return 1
        print("\nOK - all QR images present and current")
        return 0

    if written:
        print(f"generated   : {', '.join(written)}")
    else:
        print("generated   : (none - all up to date)")
    print("\nOK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())